services:
  OxidProfessionalServices\PasswordPolicy\Validators\PasswordPolicyValidatorsCollector:
    class: OxidProfessionalServices\PasswordPolicy\Validators\PasswordPolicyValidatorsCollector
    arguments:
      $validators:
        - '@OxidProfessionalServices\PasswordPolicy\Validators\PasswordPolicyOTP'
        - '@OxidProfessionalServices\PasswordPolicy\Validators\PasswordPolicyPasswordLength'
        - '@OxidProfessionalServices\PasswordPolicy\Validators\PasswordPolicyUpperLowerCase'
        - '@OxidProfessionalServices\PasswordPolicy\Validators\PasswordPolicyDigits'
        - '@OxidProfessionalServices\PasswordPolicy\Validators\PasswordPolicySpecialCharacter'
        - '@OxidProfessionalServices\PasswordPolicy\Validators\PasswordPolicyDataBreach'
    autowire: true
  OxidProfessionalServices\PasswordPolicy\Validators\PasswordPolicyPasswordLength:
    class: OxidProfessionalServices\PasswordPolicy\Validators\PasswordPolicyPasswordLength
    autowire: true;
  OxidProfessionalServices\PasswordPolicy\Validators\PasswordPolicyUpperLowerCase:
    class: OxidProfessionalServices\PasswordPolicy\Validators\PasswordPolicyUpperLowerCase
    autowire: true;
  OxidProfessionalServices\PasswordPolicy\Validators\PasswordPolicyDigits:
    class: OxidProfessionalServices\PasswordPolicy\Validators\PasswordPolicyDigits
    autowire: true;
  OxidProfessionalServices\PasswordPolicy\Validators\PasswordPolicySpecialCharacter:
    class: OxidProfessionalServices\PasswordPolicy\Validators\PasswordPolicySpecialCharacter
    autowire: true;
  OxidProfessionalServices\PasswordPolicy\Validators\PasswordPolicyDataBreach:
    class: OxidProfessionalServices\PasswordPolicy\Validators\PasswordPolicyDataBreach
    autowire: true;
  OxidProfessionalServices\PasswordPolicy\Core\PasswordPolicyConfig:
    class: OxidProfessionalServices\PasswordPolicy\Core\PasswordPolicyConfig
    autowire: true;
  OxidProfessionalServices\PasswordPolicy\Api\PasswordCheck:
    class: OxidProfessionalServices\PasswordPolicy\Api\PasswordCheck
    autowire: true;
  OxidProfessionalServices\PasswordPolicy\Validators\PasswordPolicyOTP:
    class: OxidProfessionalServices\PasswordPolicy\Validators\PasswordPolicyOTP
    autowire: true;
  PasswordPolicyAPCu:
    class: OxidProfessionalServices\PasswordPolicy\Factory\RateLimiter\PasswordPolicyAPCu
  PasswordPolicyMemcached:
    class: OxidProfessionalServices\PasswordPolicy\Factory\RateLimiter\PasswordPolicyMemcached
    autowire: true;
  DivineOmega\PasswordExposed\PasswordExposedChecker:
    class: DivineOmega\PasswordExposed\PasswordExposedChecker