services:
  OxidProfessionalServices\PasswordPolicy\Validators\PasswordPolicyValidatorsCollector:
    class: OxidProfessionalServices\PasswordPolicy\Validators\PasswordPolicyValidatorsCollector
    arguments:
      $validators:
        - '@OxidProfessionalServices\PasswordPolicy\Validators\PasswordPolicyPasswordLength'
        - '@OxidProfessionalServices\PasswordPolicy\Validators\PasswordPolicyUpperLowerCase'
        - '@OxidProfessionalServices\PasswordPolicy\Validators\PasswordPolicyDigits'
        - '@OxidProfessionalServices\PasswordPolicy\Validators\PasswordPolicySpecialCharacter'
        - '@OxidProfessionalServices\PasswordPolicy\Validators\PasswordPolicyDataBreach'
    autowire: true
  OxidProfessionalServices\PasswordPolicy\Validators\PasswordPolicyPasswordLength:
    class: OxidProfessionalServices\PasswordPolicy\Validators\PasswordPolicyPasswordLength
  OxidProfessionalServices\PasswordPolicy\Validators\PasswordPolicyUpperLowerCase:
    class: OxidProfessionalServices\PasswordPolicy\Validators\PasswordPolicyUpperLowerCase
  OxidProfessionalServices\PasswordPolicy\Validators\PasswordPolicyDigits:
    class: OxidProfessionalServices\PasswordPolicy\Validators\PasswordPolicyDigits
  OxidProfessionalServices\PasswordPolicy\Validators\PasswordPolicySpecialCharacter:
    class: OxidProfessionalServices\PasswordPolicy\Validators\PasswordPolicySpecialCharacter
  OxidProfessionalServices\PasswordPolicy\Validators\PasswordPolicyDataBreach:
    class: OxidProfessionalServices\PasswordPolicy\Validators\PasswordPolicyDataBreach