name: oxid module tests

on: [push]

jobs:
  codestyle_checks:
    strategy:
      matrix:
        php: [ 7.4 ] # [7.1, 7.2]
        oxid: [ 6.2 ]
    runs-on: ubuntu-latest
    container:
      image: oxidprojects/oxid-apache-php:oxid${{ matrix.oxid }}-php${{ matrix.php }}
    steps:
      - uses: actions/checkout@v1
      - name: Validate composer.json
        run: composer validate
      - name: validate php syntax
        run: find . -not -path "./vendor/*" -name "*.php" -print0 | xargs -0 -n1 -P8 php -l
      - name: install php-cs-fixer
        run: phive install php-cs-fixer:2.18.5 --trust-gpg-keys E82B2FB314E9906E
      - name: run code checks
        run: tools/php-cs-fixer fix --dry-run --diff-format=udiff .
  install:
    strategy:
      matrix:
        php: [ 7.4 ] # [7.1, 7.2]
        oxid: [ 6.2 ] # [
    runs-on: ubuntu-latest
    container:
      image: oxidprojects/oxid-apache-php:oxid${{ matrix.oxid }}-php${{ matrix.php }}
      options: --tmpfs=/tmp:noatime
    env:
      MODULE_NAME: oxid-professional-services/password-policy
    steps:
      - uses: actions/checkout@v1

      - name: install
        run: composer create-project oxid-professional-services/test-oxid /tmp/oxid --no-interaction -s dev --repository="{\"url\":\"https://github.com/keywan-ghadami-oxid/test-oxid.git\", \"type\":\"vcs\"}" --remove-vcs

      - name: move artifacts to projects folder
        run: |
          mkdir -p /tmp/oxid/project-modules/module-under-test && cp -r * /tmp/oxid/project-modules/module-under-test
      - name: add project module folder
        run:
          composer config repositories.build path /tmp/oxid/project-modules/\*
        working-directory: /tmp/oxid

      - name: require module
        run: cd /tmp/oxid && composer require --no-interaction $MODULE_NAME
        working-directory: /tmp/oxid

      - name: move config to source folder
        run: cp config.inc.php-dist source/config.inc.php
        working-directory: /tmp/oxid

      - name: zip temp artifact
        run: tar czf /tmp/oxid.tar.gz --directory /tmp oxid

      - name: Upload oxid-with-deps
        uses: actions/upload-artifact@v2
        with:
          name: oxid${{ matrix.oxid }}-php${{ matrix.php }}-with-deps
          path: /tmp/oxid.tar.gz

  static_code_checks:
    strategy:
      matrix:
        php: [ 7.4 ] # [7.1, 7.2]
        oxid: [ 6.2 ]
    runs-on: ubuntu-latest
    needs: install
    container:
      image: oxidprojects/oxid-apache-php:oxid${{ matrix.oxid }}-php${{ matrix.php }}
      options: --tmpfs=/tmp:exec,noatime
    env:
      MYSQL_DATABASE: oxid
      MYSQL_HOST: db
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      SHOP_URL: http://localhost/
    services:
      db:
        image: mariadb:10.5
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: oxid
        ports:
          - 3306
        options: --tmpfs=/tmp:noatime --tmpfs=/var/lib/mysql:noatime --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
    steps:
      - name: Download oxid installation
        uses: actions/download-artifact@v2
        with:
          name: oxid${{ matrix.oxid }}-php${{ matrix.php }}-with-deps
          path: /tmp
      - name: extract oxid installation
        run: |
          tar xzf oxid.tar.gz
        working-directory: /tmp/

      - name: prepare autoload
        run: |
          bin/symlinkProjectModules.sh
          bin/createModuleAutoload.sh
        working-directory: /tmp/oxid

      - name: prepare autoload
        run: bin/createModuleAutoload.sh
        working-directory: /tmp/oxid

      - name: composer validate
        run: composer validate
        working-directory: /tmp/oxid

      - name: run unit tests
        run: php tools/psalm project-modules/passwordpolicy/src source/modules/oxps/passwordpolicy/metadata.php
        working-directory: /tmp/oxid


  oxid_unit_tests:
    strategy:
      matrix:
        php: [ 7.4 ] # [7.1, 7.2]
        oxid: [ 6.2 ]
    runs-on: ubuntu-latest
    needs: install
    env:
      MYSQL_DATABASE: oxid
      MYSQL_HOST: db
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      SHOP_URL: http://localhost/
    services:
      db:
        image: mariadb:10.5
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: oxid
        ports:
          - 3306
        options: --tmpfs=/tmp:noatime --tmpfs=/var/lib/mysql:noatime --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
    container:
      image: oxidprojects/oxid-apache-php:oxid${{ matrix.oxid }}-php${{ matrix.php }}
      options: --tmpfs=/tmp:exec,noatime
    steps:
      - name: Download a single artifact
        uses: actions/download-artifact@v2
        with:
          name: oxid${{ matrix.oxid }}-php${{ matrix.php }}-with-deps
          path: /tmp
      - name: extract temp artifact
        run: |
          tar xzf oxid.tar.gz
        working-directory: /tmp/
      - name: prepare autoload
        run: |
          bin/symlinkProjectModules.sh
          bin/createModuleAutoload.sh
        working-directory: /tmp/oxid

      - name: mysql shema
        run: mysql -u $MYSQL_USER -h db -p$MYSQL_PASSWORD $MYSQL_DATABASE < "vendor/oxid-esales/oxideshop-ce/source/Setup/Sql/database_schema.sql"
        working-directory: /tmp/oxid

      - name: mysql data
        run: mysql -u $MYSQL_USER -h db -p$MYSQL_PASSWORD $MYSQL_DATABASE < "vendor/oxid-esales/oxideshop-ce/source/Setup/Sql/initial_data.sql"
        working-directory: /tmp/oxid

      - name: console
        run: vendor/bin/oe-console oe:module:activate oxpspasswordpolicy
        working-directory: /tmp/oxid

      - name: check mod config
        run: cat var/configuration/shops/1.yaml
        working-directory: /tmp/oxid

      - name: composer validate
        run: composer validate
        working-directory: /tmp/oxid

      - name: oxid config
        run: cat source/config.inc.php
        working-directory: /tmp/oxid

      - name: run unit tests
        run: php vendor/bin/phpunit --bootstrap vendor/oxid-esales/testing-library/bootstrap.php -c /tmp/oxid/source/modules/oxps/passwordpolicy/tests/phpunit.xml
        working-directory: /tmp/oxid
